version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: documentation
    versions:
    - 13.1.1
    - 13.2.0
    - 13.2.1
    - 13.2.4
  - dependency-name: electron
    versions:
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: p-timeout
    versions:
    - 4.1.0
